### ISSUE TITLE
禁用重复任务及QQ星海牧场BUG

### ISSUE THREAD

**Issue by dnxbice** [KingRan/KR#1]
感谢大神重新开了库，我拉了新库跑，由于我没有删除旧库所以运行禁用重复任务的时候把新库全部都禁用掉，我看了一下是过滤那个名称没有改，还是KingRan_JDJB，改了就可以了
但是QQ星系牧场每次执行完都会有3到4个通知，不知道哪里的问题？

**Comment by Hb19910927** [comment]
> 感谢大神重新开了库，我拉了新库跑，由于我没有删除旧库所以运行禁用重复任务的时候把新库全部都禁用掉，我看了一下是过滤那个名称没有改，还是KingRan_JDJB，改了就可以了 但是QQ星系牧场每次执行完都会有3到4个通知，不知道哪里的问题？

看一下定时，改下，删除一个*就行

**Comment by JohnFreeman9** [comment]
刚要上来提这个issue，就发现你这提出了。
QQ星那个多打了个*导致执行频率实际上三五分钟就一次，每天刷几十条通知= =
建议手动删除一个*

**Comment by musk-1024** [comment]
今天跑了一下，感觉有些脚本没必要通知，请问该怎么设置脚本是否发送通知

**Comment by coolguy001tv** [comment]
> 今天跑了一下，感觉有些脚本没必要通知，请问该怎么设置脚本是否发送通知
参考一下：
`export NOTIFY_SKIP_TEXT="星系牧场"`

记得多个不要的中间应该是@

**Comment by musk-1024** [comment]
> > 今天跑了一下，感觉有些脚本没必要通知，请问该怎么设置脚本是否发送通知
> 
> 参考一下： `export NOTIFY_SKIP_TEXT="星系牧场"`
> 
> 记得多个不要的中间应该是@
> 
> @musk-1024

我这边测试了一下好像不行，我把这个添加到配置文件里了，但是不起作用
