### ISSUE TITLE
京东红包凌晨1点多被人以还有代付形式使用了

### ISSUE THREAD

**Issue by python0707** [KingRan/KR#111]
11号到期的红包，再10日凌晨1点多被人以好友代付的形式套走了，没有开免密支付，京东账号还有好几千的E卡都没有被消费，是不是脚本现在有问题了？

**Comment by weishaopenggege** [comment]
每次看到你们这被偷那被偷,我都怀疑我的账号有多不配啊? 而且, 今天才10号, 11日凌晨套你的红包?嗯哼?

**Comment by google-mirror** [comment]
> 11号到期的红包，再10日凌晨1点多被人以好友代付的形式套走了，没有开免密支付，京东账号还有好几千的E卡都没有被消费，是不是脚本现在有问题了？

直接报警找京东

**Comment by EchoChan314** [comment]
你确定你只用这个库？没用其它的第三方京东工具？
别找错人了。

**Comment by python0707** [comment]
> 

只用这个库，没有用过其他的，已经用了好几个月了，就这一次，以好友代付的形式给弄走了

**Comment by google-mirror** [comment]
> > 
> 
> 只用这个库，没有用过其他的，已经用了好几个月了，就这一次，以好友代付的形式给弄走了

你咋发现的

**Comment by python0707** [comment]
> > > 
> > 
> > 
> > 只用这个库，没有用过其他的，已经用了好几个月了，就这一次，以好友代付的形式给弄走了
> 
> 你咋发现的

京东右上角，消息，第一个交易物流里查到了，收货人地址是浙江省绍兴市，收货人屠克登，手机号是131****9869，购买商品是游戏教学陪练，店铺名称是绘蓝教育培训专营店

**Comment by weishaopenggege** [comment]
> 



> > > > 
> > > 
> > > 
> > > 只用这个库，没有用过其他的，已经用了好几个月了，就这一次，以好友代付的形式给弄走了
> > 
> > 
> > 你咋发现的
> 
> 京东右上角，消息，第一个交易物流里查到了，收货人地址是浙江省绍兴市，收货人屠克登，手机号是131****9869，购买商品是游戏教学陪练，店铺名称是绘蓝教育培训专营店

除了红包, 有花你其他资金吗?看起来有点可怕, 你有搞那个 wsck 的东西吗?

**Comment by python0707** [comment]
> > 
> 
> > > > > 
> > > > 
> > > > 
> > > > 只用这个库，没有用过其他的，已经用了好几个月了，就这一次，以好友代付的形式给弄走了
> > > 
> > > 
> > > 你咋发现的
> > 
> > 
> > 京东右上角，消息，第一个交易物流里查到了，收货人地址是浙江省绍兴市，收货人屠克登，手机号是131****9869，购买商品是游戏教学陪练，店铺名称是绘蓝教育培训专营店
> 
> 除了红包, 有花你其他资金吗?看起来有点可怕, 你有搞那个 wsck 的东西吗?

其他的没有，E卡都没有花，搞了wsck

**Comment by weishaopenggege** [comment]
> > > 
> > 
> > 
> > > > > > 
> > > > > 
> > > > > 
> > > > > 只用这个库，没有用过其他的，已经用了好几个月了，就这一次，以好友代付的形式给弄走了
> > > > 
> > > > 
> > > > 你咋发现的
> > > 
> > > 
> > > 京东右上角，消息，第一个交易物流里查到了，收货人地址是浙江省绍兴市，收货人屠克登，手机号是131****9869，购买商品是游戏教学陪练，店铺名称是绘蓝教育培训专营店
> > 
> > 
> > 除了红包, 有花你其他资金吗?看起来有点可怕, 你有搞那个 wsck 的东西吗?
> 
> 其他的没有，E卡都没有花，搞了wsck

看其他人也都说搞了wsck很容易出问题, 我一直没有搞, 一个月手动更新一下cookie, 没有出现过被偷东西的情况,

**Comment by google-mirror** [comment]
你的支付密码是不是很简单

**Comment by liu269569205** [comment]
最近这两天 很多人京豆被盗买了，作者的加密脚本有鬼

**Comment by liu269569205** [comment]
我朋友去客服反应的，客服回电话说京东报警处理这件事了，搞盗刷这次要倒霉了，和上次偷京豆打赏一样结局

**Comment by google-mirror** [comment]
老老实实改支付密码, 关免密支付, 如果这样还被偷, 就有鬼了

**Comment by ryan016** [comment]
被盗窃的无门槛红包都是“绘蓝教育培训专营店”的，店家肯定有问题。

**Comment by SuperKingi** [comment]
一样被偷撸了20红包

**Comment by yuebanyidiudiu** [comment]
我只运行了几个收豆豆的js，没用wskey

**Comment by weishaopenggege** [comment]
> 京豆被盗 购买了[哇京够旗舰店] 沃尔玛卡20元面值

你有设置wsck么?

**Comment by weishaopenggege** [comment]
> 一样被偷撸了20红包

你有设置wsck么?

**Comment by google-mirror** [comment]
#81 #107

**Comment by python0707** [comment]
更新下最新进展，通过订单信息，已经从店家那把红包以微信转账的形式退回来了。这个店家有很大的嫌疑，不停的问我是怎么查到的订单信息和核销码

**Comment by pandorays** [comment]
怎么查询？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KingRan/KR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月11日(星期三) 中午12:38
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [KingRan/KR] 京东红包凌晨1点多被人以还有代付形式使用了 (Issue #111)





 
更新下最新进展，通过订单信息，已经从店家那把红包以微信转账的形式退回来了。这个店家有很大的嫌疑，不停的问我是怎么查到的订单信息和核销码

**Comment by python0707** [comment]
红包已要回，已经换库

**Comment by google-mirror** [comment]
> 更新下最新进展，通过订单信息，已经从店家那把红包以微信转账的形式退回来了。这个店家有很大的嫌疑，不停的问我是怎么查到的订单信息和核销码

那岂不是可以和商家合作套现红包

**Comment by weishaopenggege** [comment]
> 红包已要回，已经换库

能告诉一下换谁的库吗
