### ISSUE TITLE
你们的京东APP会退出登陆吗

### ISSUE THREAD

**Issue by google-mirror** [KingRan/KR#118]
京东APP自动退出登陆, 之前获取全部COOKIES失效, 没有修改过密码或者在其他设备登陆, 是京东定期退出还是有人在暴力破解支付密码?

**Comment by KingRan** [comment]
会，京东搞事。强制退出

**Comment by google-mirror** [comment]
> 会，京东搞事。强制退出

应该是某个脚本触发了强制登出逻辑, 没用脚本的号是不会的
