### ISSUE TITLE
提示初始化农场数据异常

### ISSUE THREAD

**Issue by 1042187809** [KingRan/KR#12]
中午12点还正常的，不止我一个人出现这个状况，用的青龙

**Comment by ni11gg** [comment]
是的,我也出现了.你解决了吗

**Comment by KingRan** [comment]
已经修正

**Comment by ni11gg** [comment]
<img width="478" alt="image" src="https://github.com/KingRan/KR/assets/22385605/78975d69-9d39-4705-9a32-6350ff713356">
今天试了,还是不行哎.
全删了还重新拉库了,也不行.

**Comment by cylupel** [comment]
同样问题

**Comment by KingRan** [comment]
> <img alt="image" width="478" src="https://user-images.githubusercontent.com/22385605/263433950-78975d69-9d39-4705-9a32-6350ff713356.png"> 今天试了,还是不行哎. 全删了还重新拉库了,也不行.

你这是没有更新  新版不是这个提示

**Comment by ni11gg** [comment]
> > <img alt="image" width="478" src="https://user-images.githubusercontent.com/22385605/263433950-78975d69-9d39-4705-9a32-6350ff713356.png"> 今天试了,还是不行哎. 全删了还重新拉库了,也不行.
> 
> 你这是没有更新 新版不是这个提示

更新是重新拉库就可以吗？

**Comment by wangbing004** [comment]
删了重新拉库也不行, 还是这个提示
