### ISSUE TITLE
大佬，activity文件夹里面的脚本不会添加进定时任务

### ISSUE THREAD

**Issue by philly1021** [KingRan/KR#132]
大佬，activity文件夹里面的脚本不会添加进定时任务

我拉库命令用的是telegram里面的，系统文件夹里也看得到任务，青龙面板里面看不到，定时任务里面也没有

是本身就是这样的设定吗，还是我哪里出了问题

![image](https://user-images.githubusercontent.com/34532110/170277515-c24c9ba3-2fe1-4f80-b5fb-0a16cd9a774a.png)
![image](https://user-images.githubusercontent.com/34532110/170277744-5eaf7aa4-f7f8-4eca-909b-9dadc798a1bf.png)
![image](https://user-images.githubusercontent.com/34532110/170277931-292080f7-a2f2-42b4-a9ad-f2706f02bd35.png)

**Comment by KingRan** [comment]
> 大佬，activity文件夹里面的脚本不会添加进定时任务
> 
> 我拉库命令用的是telegram里面的，系统文件夹里也看得到任务，青龙面板里面看不到，定时任务里面也没有
> 
> 是本身就是这样的设定吗，还是我哪里出了问题
> 
> ![image](https://user-images.githubusercontent.com/34532110/170277515-c24c9ba3-2fe1-4f80-b5fb-0a16cd9a774a.png)
> ![image](https://user-images.githubusercontent.com/34532110/170277744-5eaf7aa4-f7f8-4eca-909b-9dadc798a1bf.png)
> ![image](https://user-images.githubusercontent.com/34532110/170277931-292080f7-a2f2-42b4-a9ad-f2706f02bd35.png)
> 

一般来说   这个文件夹我是用来存档过期无用脚本的

**Comment by philly1021** [comment]
明白了，感谢大佬
