### ISSUE TITLE
领现金被谁提了？作者可以出来解释一下吗

### ISSUE THREAD

**Issue by usgate** [KingRan/KR#151]
xxx

**Comment by fengchenzhihun1** [comment]
怎么不长个脑子，绑定得是你自己的微信号，体现的时候也是打开你自己的微信号去体现，你在问谁那；

**Comment by google-mirror** [comment]
> 怎么不长个脑子，绑定得是你自己的微信号，体现的时候也是打开你自己的微信号去体现，你在问谁那；

可以提现到任意实名微信, 不需要绑定

**Comment by usgate** [comment]
> 怎么不长个脑子，绑定得是你自己的微信号，体现的时候也是打开你自己的微信号去体现，你在问谁那；

你这是张口就来的吗？看下 #110

**Comment by enoxunil** [comment]
> 怎么不长个脑子，绑定得是你自己的微信号，体现的时候也是打开你自己的微信号去体现，你在问谁那；

git都知道怎么上来，还是拍脑袋就喷，判断力和思维习惯真是堪忧

我的东东萌宠领现金也被其他人提了

**Comment by KingRan** [comment]
我只能建议你不要使用本库。
