### ISSUE TITLE
东东农场任务请求间隔时间太大，导致脚本运行时间N倍增加

### ISSUE THREAD

**Issue by Kaystar** [KingRan/KR#16]
不知是否有变量可以控制这个任务请求间隔时间，现在的情况是早上第一次运行任务脚本，10个号跑了4个小时。。。。

还有东东农场内部水滴互助脚本也是这样

**Comment by li3637** [comment]
6个号：早上耗时 8004 秒，中午耗时 2203 秒

**Comment by Kaystar** [comment]
> 延迟已经降低了

比之前稍微快一丢丢。。。。现在早上第一次任务是4个小时跑了13个号
