### ISSUE TITLE
东东萌宠-领现金 这个问题作者有必要出来回应一下

### ISSUE THREAD

**Issue by enoxunil** [KingRan/KR#160]
@KingRan @KingRan888 
维护脚本不易，作者可以明确在库中说明提现金作为维护成本，或者通过环境变量让用户自主选择
偷偷的提确实不太合适，换句话说，cookie怎么放心交给此库。京东金融有很多衍生产品，指不定搞出什么大动作。
顺便说一下，我只用了此库，并未拉取其它任何脚本

**Comment by KingRan** [comment]
建议不要使用本库。我解释不了也不想解释。本人行得正坐得直，不做龌龊之事。

**Comment by enoxunil** [comment]
那就是有其他脚本，或者青龙本身存在漏洞或者问题，只能这样解释了？
