### ISSUE TITLE
有人被登录后台了吗

### ISSUE THREAD

**Issue by puber-from-alien** [KingRan/KR#17]
青龙后台被登录了，IP来源是我当前的公网IP，设备在NAT下按理说不应该能被登录上啊

**Comment by qiqiandfei** [comment]
修改下默认端口就行了

**Comment by weishaopenggege** [comment]
> 青龙后台被登录了，IP来源是我当前的公网IP，设备在NAT下按理说不应该能被登录上啊

兄弟, 怎么找到问题了吗? 我今天也出现这种情况了

**Comment by qq854051086** [comment]
+1

**Comment by zhucaidan** [comment]
同+1，是不是哪个定时脚本有远程控制代码

**Comment by wangsongyan** [comment]
+1，所以我开了两步认证

**Comment by xi008** [comment]
同样的问题，被自己的服务器IP登录

**Comment by bertms** [comment]
加两步验证 屏蔽IP访问

**Comment by zhucaidan** [comment]
> 加两步验证 屏蔽IP访问

试了没用，他应该是某个脚本执行了更改docker里linux系统的密码或者漏洞来登录的

**Comment by google-mirror** [comment]
删除脚本

**Comment by weishaopenggege** [comment]
> 删除脚本

删除哪个脚本啊? 有大佬解决了吗

**Comment by davidcelery** [comment]
同问，各位大佬找到问题所在没~
