### ISSUE TITLE
已解决

### ISSUE THREAD

**Issue by w900316** [KingRan/KR#177]
## 开始执行... 2022-06-21 11:30:00

开始更新仓库：/ql/repo/KingRan_KR

Fetching origin
HEAD is now at cbd2d5f 更新
Already up to date.

更新/ql/repo/KingRan_KR成功...

检测到有失效的定时任务：

KingRan_KR/jd_carplay.js
KingRan_KR/jd_mfredrain.js
KingRan_KR/jd_opencardL155.js
KingRan_KR/jd_opencardL164.js
KingRan_KR/jd_opencardL175.js
KingRan_KR/jd_opencardL176.js
KingRan_KR/jd_opencardL185_1.js
KingRan_KR/jd_opencardL186.js
KingRan_KR/jd_opencardL187_1.js
KingRan_KR/jd_opencardL188.js
KingRan_KR/jd_pigPet.js

**Comment by huoshenw** [comment]
为什么不会自动删除 求指点
