### ISSUE TITLE
农场任务报错是什么原因

### ISSUE THREAD

**Issue by sofs2005** [KingRan/KR#18]
所有号都报错了：初始化农场数据异常, 请登录京东 app查看农场0元水果功能是否正常。
登陆app看是正常的

**Comment by aa1049372051** [comment]
我也是报错，大概从20号开始的把，之前是好的

**Comment by wangmt2000** [comment]
删了原来的容器，使用新版QL，同时也换了服务器IP。现在正常了

**Comment by sofs2005** [comment]
更新了青龙，现在可以跑了

**Comment by jianghaodn** [comment]
我的不知道什么时候掉了，然后今天发现了我就重新拉库了就好了。以前的定时拉库每个月才拉一次，现在修改为每三天拉一次了
