### ISSUE TITLE
请问大佬现在知道还有哪些助力池吗?

### ISSUE THREAD

**Issue by MrZhongzq** [KingRan/KR#183]
如题,我之前的助力池停止服务了,请问大佬有无第三方助力池的渠道,我就一个账号内部互助不起来.

**Comment by KingRan** [comment]
现在好像都是内部互助

**Comment by xhanglizhu** [comment]
新手求教，内部互助的意思是，自己备N个账号，获取助力码来实现助力的吗？ 还是说N个账号有Cookie就行？
