### ISSUE TITLE
执行自动拉库任务导致好多任务被删除

### ISSUE THREAD

**Issue by Peter-90** [KingRan/KR#209]
青龙面板版本：v2.13.8
docker版本：
![iShot_2022-08-16_10 13 34](https://user-images.githubusercontent.com/22003137/184783927-6226c7fb-d80b-474e-947c-9363ce3f6de4.png)
 使用改命令安装的青龙：
docker run -dit \
    -v $PWD/ql/config:/ql/config \
    -v $PWD/ql/log:/ql/log \
    -v $PWD/ql/db:/ql/db \
    -p 5700:5700 \
    --name qinglong \
    --hostname qinglong \
    --restart always \
    whyour/qinglong:latest
跑在本机的docker容器里面
没有使用docker-compose，也没有切docker的源地址，只用了上述命令安装之后接在docker应用的里面运行的，docker跑在本地自己的电脑上

### 下面是我用到的几个库和拉库命令：
![iShot_2022-08-16_10 04 57](https://user-images.githubusercontent.com/22003137/184783023-3f472592-fd5f-40a3-889a-af4464311614.png)
![iShot_2022-08-16_09 57 10](https://user-images.githubusercontent.com/22003137/184783026-b964f783-49d0-45ab-8a66-4fff273c8fbb.png)

**从昨天半夜一点执行拉kr库任务的时候bark从1点到2点收到很多类似这样的提示信息：**
![IMG_7813](https://user-images.githubusercontent.com/22003137/184783139-7530ab4c-9a97-4763-9781-7afe6d22e0f4.PNG)
![IMG_6F77071C3900-1](https://user-images.githubusercontent.com/22003137/184783151-8ce82840-b864-4428-bd9c-a3213a23d70a.jpeg)
### 只有少数几个添加任务的推送：
![IMG_0ED68DA8D423-1](https://user-images.githubusercontent.com/22003137/184783264-d2cc8cf6-7a2d-43aa-a1d9-1dba00d62f93.jpeg)

该问题导致少了很多定时任务，最后只要十几个任务在跑了，目前原因尚未找到，麻烦大佬能看一下吗？确认是一下是bug还是我个人的配置原因

通过这两天的观察我发现跟什么时候拉库没有关系，每天晚上1点都会执行删除的操作，然后任务就变少了

**Comment by cddjr** [comment]
说个题外话，既然都在用青龙2.13了，怎么不在订阅管理页面进行仓库的更新呢？

**Comment by Peter-90** [comment]
@cddjr 好的 我试试看 感觉跟这个关系不大 我发现是1点自动执行的

**Comment by hecarli555** [comment]
> @cddjr 好的 我试试看 感觉跟这个关系不大 我发现是1点自动执行的

大佬问一下你问题解决没有？我现在拉去仓库连任务都建立不起来。。。

**Comment by hellooldtimes** [comment]
> > @cddjr 好的 我试试看 感觉跟这个关系不大 我发现是1点自动执行的
> 
> 大佬问一下你问题解决没有？我现在拉去仓库连任务都建立不起来。。。

你解决了吗？

**Comment by hecarli555** [comment]
问题依旧，换了几个代理还是不行



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: hellooldtimes ***@***.***&gt;
发送时间: 2022年8月29日 22:36
收件人: KingRan/KR ***@***.***&gt;
抄送: hecarli555 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [KingRan/KR] 执行自动拉库任务导致好多任务被删除 (Issue #209)






@cddjr 好的 我试试看 感觉跟这个关系不大 我发现是1点自动执行的

大佬问一下你问题解决没有？我现在拉去仓库连任务都建立不起来。。。

你解决了吗？

**Comment by hellooldtimes** [comment]
> 问题依旧，换了几个代理还是不行 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: hellooldtimes ***@***.***&gt; 发送时间: 2022年8月29日 22:36 收件人: KingRan/KR ***@***.***&gt; 抄送: hecarli555 ***@***.***&gt;, Comment ***@***.***&gt; 主题: Re: [KingRan/KR] 执行自动拉库任务导致好多任务被删除 (Issue #209) @cddjr 好的 我试试看 感觉跟这个关系不大 我发现是1点自动执行的 大佬问一下你问题解决没有？我现在拉去仓库连任务都建立不起来。。。 你解决了吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

我也是任务都没了，，，，不知道咋办
