### ISSUE TITLE
Bark消息推送问题，在sendnotify文件中自己加上了level=passive，但是只要从新拉取就会更新掉

### ISSUE THREAD

**Issue by TrisAXJ** [KingRan/KR#213]
我试过了在ql repo命令里面把sendnotify放在不拉取中 好像不起作用，可能是我放错地方了，希望大佬能够指导一下不拉取新的sendnotify。
或者能直接在bark消息推送里面加个时效性通知选项，想让推送不亮屏提醒，但还在通知列表中。

**Comment by cddjr** [comment]
青龙默认会强制替换仓库中的推送脚本。

一种方案是直接把青龙自带的sendnotify替换成你需要的，这样无论拉什么仓库都是这个sendnotify替换。
自带的在/ql/data/deps/ (如果是v2.12之前的老版本青龙，去掉路径中的/data)

还有一种方案是在订阅管理里面配置【执行后】命令，这样每次更新仓库后总是会用仓库中自带的sendnotify文件
截图是我的配置，参考底部。 命令适用于v2.12以上青龙，老青龙删掉/data
cd /ql/data/repo/KingRan_KR/
cp -f sendNotify.js /ql/data/scripts/KingRan_KR/
![ql_kr](https://user-images.githubusercontent.com/802181/186383958-46afe006-d626-42f7-aec1-de5a61031b94.gif)

**Comment by TrisAXJ** [comment]
感谢解答，已经解决，谢谢

**Comment by xuexijiaoben** [comment]
> 青龙默认会强制替换仓库中的推送脚本。
> 
> 简单粗暴的解决方法是把青龙自带的sendnotify替换成你需要的，这样无论拉什么仓库都是你的sendnotify。
> 
>     * 青龙自带脚本保存在/ql/data/deps/内 (如果是v2.12之前的老版本青龙，需要去掉路径中的/data)
> 
> 
> 如果你是v2.13.0以上版本的青龙，可以在订阅管理里面配置【执行后】命令。
> 
> ```
> 比如总是用仓库的sendnotify.js的命令如下
> cp -f /ql/data/repo/KingRan_KR/sendNotify.js /ql/data/scripts/KingRan_KR/
> ```
> 
> ![ql_kr](https://user-images.githubusercontent.com/802181/186383958-46afe006-d626-42f7-aec1-de5a61031b94.gif) [ ![ql_kr](https://user-images.githubusercontent.com/802181/186383958-46afe006-d626-42f7-aec1-de5a61031b94.gif) ](https://user-images.githubusercontent.com/802181/186383958-46afe006-d626-42f7-aec1-de5a61031b94.gif) [ ](https://user-images.githubusercontent.com/802181/186383958-46afe006-d626-42f7-aec1-de5a61031b94.gif)

大神，能帮我解释下这么多sendNotify.js的关系么，我看目录下好多地方有
1.ql/data/deps/sendNotify.js
2.ql/data/scripts/sendNotify.js
3.ql/data/scripts/KingRan_KR/sendNotify.js
4.ql/data/scripts/KingRan_KR/function/sendNotify.js
5.ql/data/repo/KingRan_KR/sendNotify.js
6.ql/data/repo/KingRan_KR/function/sendNotify.js

这些sendNotify.js，哪个是优先调用的呀

**Comment by wangsq5026** [comment]
> 青龙默认会强制替换仓库中的推送脚本。
> 
> 简单粗暴的解决方法是把青龙自带的sendnotify替换成你需要的，这样无论拉什么仓库都是你的sendnotify。
> 
> * 青龙自带脚本保存在/ql/data/deps/内 (如果是v2.12之前的老版本青龙，需要去掉路径中的/data)
> 
> 如果你是v2.13.0以上版本的青龙，可以在订阅管理里面配置【执行后】命令。
> 
> ```
> 比如总是用仓库的sendnotify.js的命令如下
> cp -f /ql/data/repo/KingRan_KR/sendNotify.js /ql/data/scripts/KingRan_KR/
> ```
> 
> ![ql_kr](https://user-images.githubusercontent.com/802181/186383958-46afe006-d626-42f7-aec1-de5a61031b94.gif) [ ![ql_kr](https://user-images.githubusercontent.com/802181/186383958-46afe006-d626-42f7-aec1-de5a61031b94.gif) ](https://user-images.githubusercontent.com/802181/186383958-46afe006-d626-42f7-aec1-de5a61031b94.gif) [ ](https://user-images.githubusercontent.com/802181/186383958-46afe006-d626-42f7-aec1-de5a61031b94.gif)

**执行后状态栏里面填写下面这个命令      运行成功!
cp -f /ql/data/repo/KingRan_KR/sendNotify.js /ql/data/scripts/KingRan_KR/**

**Comment by cddjr** [comment]
> > 青龙默认会强制替换仓库中的推送脚本。
> > 简单粗暴的解决方法是把青龙自带的sendnotify替换成你需要的，这样无论拉什么仓库都是你的sendnotify。
> > 
> > * 青龙自带脚本保存在/ql/data/deps/内 (如果是v2.12之前的老版本青龙，需要去掉路径中的/data)
> > 
> > 如果你是v2.13.0以上版本的青龙，可以在订阅管理里面配置【执行后】命令。
> > ```
> > 比如总是用仓库的sendnotify.js的命令如下
> > cp -f /ql/data/repo/KingRan_KR/sendNotify.js /ql/data/scripts/KingRan_KR/
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![ql_kr](https://user-images.githubusercontent.com/802181/186383958-46afe006-d626-42f7-aec1-de5a61031b94.gif)
> >       
> >         [
> >           
> >             ![ql_kr](https://user-images.githubusercontent.com/802181/186383958-46afe006-d626-42f7-aec1-de5a61031b94.gif)
> >           
> >         ](https://user-images.githubusercontent.com/802181/186383958-46afe006-d626-42f7-aec1-de5a61031b94.gif)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/802181/186383958-46afe006-d626-42f7-aec1-de5a61031b94.gif)
> >         
> >        [ ![ql_kr](https://user-images.githubusercontent.com/802181/186383958-46afe006-d626-42f7-aec1-de5a61031b94.gif) ](https://user-images.githubusercontent.com/802181/186383958-46afe006-d626-42f7-aec1-de5a61031b94.gif)
> >       
> >         [
> >           
> >             ![ql_kr](https://user-images.githubusercontent.com/802181/186383958-46afe006-d626-42f7-aec1-de5a61031b94.gif)
> >           
> >         ](https://user-images.githubusercontent.com/802181/186383958-46afe006-d626-42f7-aec1-de5a61031b94.gif)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/802181/186383958-46afe006-d626-42f7-aec1-de5a61031b94.gif)
> >         
> >        [ ](https://user-images.githubusercontent.com/802181/186383958-46afe006-d626-42f7-aec1-de5a61031b94.gif)
> 
> 执行后状态栏里面仅仅填写下面这个命令 运行成功!
> 
> cp -f /ql/data/repo/KingRan_KR/sendNotify.js /ql/data/scripts/KingRan_KR/
> 
> 楼主填的 cd ********* 没有测试

cd 那个是我这里的一些额外需求，直接用我文字提供的命令即可。
