### ISSUE TITLE
ERROR: task KingRan_KR/jd_bean_change_pro.js

### ISSUE THREAD

**Issue by happy-func** [KingRan/KR#27]
Bark APP发送通知调用API失败！！

HTTPError: Response code 431 (Request Header Fields Too Large)
    at Request.<anonymous> (/ql/scripts/node_modules/.pnpm/registry.npmmirror.com+got@11.8.3/node_modules/got/dist/source/as-promise/index.js:117:42)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_NON_2XX_3XX_RESPONSE',
  timings: {
    start: 1646052465238,
    socket: 1646052465238,
    lookup: 1646052465239,
    connect: 1646052466272,
    secureConnect: 1646052466336,
    upload: 1646052466336,
    response: 1646052466498,
    end: 1646052466498,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 0,
      dns: 1,
      tcp: 1033,
      tls: 64,
      request: 0,
      firstByte: 162,
      download: 0,
      total: 1260
    }
  }
}

**Comment by KingRan** [comment]
Bark APP 不太清楚  没用过  

通知文件来源于：https://t.me/ccwav

**Comment by happy-func** [comment]
> Bark APP 不太清楚 没用过
> 
> 通知文件来源于：https://t.me/ccwav

今个看推送又正常了，就这吧
