### ISSUE TITLE
极速版汪汪赛跑报错

### ISSUE THREAD

**Issue by afeng116** [KingRan/KR#279]
![3CBE3D96-F451-4976-857E-8E71F264FAB0](https://user-images.githubusercontent.com/61038102/205451815-d0559e0a-075d-45d4-bd7f-33c341f4a33a.jpeg)

**Comment by 204219108** [comment]
解决了嘛  我的也是这样

**Comment by 204219108** [comment]
> ![3CBE3D96-F451-4976-857E-8E71F264FAB0](https://user-images.githubusercontent.com/61038102/205451815-d0559e0a-075d-45d4-bd7f-33c341f4a33a.jpeg)

解决了嘛 我的也这样

**Comment by 204219108** [comment]
> 没有，大佬没回我

确认了  是axios的问题  安装0.27.2版本

**Comment by afeng116** [comment]
确实，更新了一下就好了
