### ISSUE TITLE
服务器资源异常警告是哪个脚本带来的啊？找不到关不掉

### ISSUE THREAD

**Issue by msn1983aa** [KingRan/KR#281]
我得nas用的比较狠，所以资源一直占用高，这个警告一天出来十几遍，求作者帮忙看看关哪个脚本

服务器资源异常警告
2022-12-13
智能助手
当前CPU占用 83% 内存占用 21% 磁盘占用 62%

**Comment by kingsancs** [comment]
服务器资源异常警告

当前CPU占用 82% 内存占用 36% 磁盘占用 4% 
资源占用详情 

 PID     %VSZ  %CPU COMMAND
26437     0%  17% jq -r .value
26426     0%  12% jq -r .value
26404     0%  10% jq -r .value
26396     0%  7% jq -r .value
26439     0%  7% jq -r .value
26354     0%  5% jq -r .value
26201     0%  2% bash /usr/local/bin/task KingRan_KR/jd_unsubscribe.js
26208     0%  2% bash /usr/local/bin/task KingRan_KR/jd_gold_creation.js
185     32%  0% node /ql/static/build/app.js

异常情况如上，不知道是哪个脚本

**Comment by CN-YoungYang** [comment]
![image](https://user-images.githubusercontent.com/25340441/209753208-ad03fb8f-c2ae-4630-8885-0b68370af4b9.png)

应该是面板自带的

**Comment by msn1983aa** [comment]
> ![image](https://user-images.githubusercontent.com/25340441/209753208-ad03fb8f-c2ae-4630-8885-0b68370af4b9.png)
> 
> 应该是面板自带的

找了一下我的config文件没有这一段，青龙是V2.15.4

**Comment by CN-YoungYang** [comment]
https://github.com/whyour/qinglong/issues/1714  

你要不加上去，看看

**Comment by msn1983aa** [comment]
> [whyour/qinglong#1714](https://github.com/whyour/qinglong/issues/1714)
> 
> 你要不加上去，看看

原来是这样，已设为100，这样就关掉了
