### ISSUE TITLE
无法拉库

### ISSUE THREAD

**Issue by LONELYLI666** [KingRan/KR#287]
## 开始执行... 2022-12-23 12:02:51

开始克隆仓库 https://github.com/KingRan/KR.git 到 /ql/data/repo/KingRan_KR

Cloning into '/ql/data/repo/KingRan_KR'...

fatal: Out of memory, malloc failed (tried to allocate 524288000 bytes)

fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

更新/ql/data/repo/KingRan_KR失败，请检查网络...

**Comment by narugakuru** [comment]
我也遇到了同样的问题，把ql挂载到tf卡还是显示内存不够
