### ISSUE TITLE
Bark通知失败有大佬知道怎么破吗？内容太多了就会失败

### ISSUE THREAD

**Issue by Nick12010** [KingRan/KR#84]
![image](https://user-images.githubusercontent.com/40687004/163301513-ee4861b1-e788-4726-9f2b-5226d10bda8d.png)

**Comment by ichimokuRen** [comment]
因为他使用的get请求方式发送的，你需要手动去改成post请求方式
sendNotify.js

function BarkNotify(text, desp, params = {}) {
  return new Promise((resolve) => {
    if (BARK_PUSH) {
      const options = {
        url: `${BARK_PUSH}`,
        body: `title=${encodeURIComponent(text)}&body=${encodeURIComponent(desp)}`,
        headers: {
          'Content-Type': 'application/x-www-form-urlencoded',
        },
      };
      $.post(options, (err, resp, data) => {
        try {
          if (err) {
            console.log('Bark APP发送通知调用API失败！！\n');
            console.log(err);
          } else {
            data = JSON.parse(data);
            if (data.code === 200) {
              console.log('Bark APP发送通知消息成功🎉\n');
            } else {
              console.log(`${data.message}\n`);
            }
          }
        } catch (e) {
          $.logErr(e, resp);
        } finally {
          resolve();
        }
      });
    } else {
      resolve();
    }
  });
}
      $.post(options, (err, resp, data) => {
        try {
          if (err) {
            console.log('Bark APP发送通知调用API失败！！\n');
            console.log(err);
          } else {
            data = JSON.parse(data);
            if (data.code === 200) {
              console.log('Bark APP发送通知消息成功🎉\n');
            } else {
              console.log(`${data.message}\n`);
            }
          }
        } catch (e) {
          $.logErr(e, resp);
        } finally {
          resolve();
        }
      });
    } else {
      resolve();
    }
  });
}`

**Comment by Nick12010** [comment]
> 因为他使用的get请求方式发送的，你需要手动去改成post请求方式 sendNotify.js
> 
> function BarkNotify(text, desp, params = {}) { return new Promise((resolve) => { if (BARK_PUSH) { const options = { url: `${BARK_PUSH}`, body: `title=${encodeURIComponent(text)}&body=${encodeURIComponent(desp)}`, headers: { 'Content-Type': 'application/x-www-form-urlencoded', }, }; $.post(options, (err, resp, data) => { try { if (err) { console.log('Bark APP发送通知调用API失败！！\n'); console.log(err); } else { data = JSON.parse(data); if (data.code === 200) { console.log('Bark APP发送通知消息成功tada\n'); } else { console.log(`${data.message}\n`); } } } catch (e) { $.logErr(e, resp); } finally { resolve(); } }); } else { resolve(); } }); } $.post(options, (err, resp, data) => { try { if (err) { console.log('Bark APP发送通知调用API失败！！\n'); console.log(err); } else { data = JSON.parse(data); if (data.code === 200) { console.log('Bark APP发送通知消息成功tada\n'); } else { console.log(`${data.message}\n`); } } } catch (e) { $.logErr(e, resp); } finally { resolve(); } }); } else { resolve(); } }); }`

我直接把get改为post不行呢？

**Comment by ichimokuRen** [comment]
你行你自己上啊，跑来问什么，搞笑

**Comment by Nick12010** [comment]
.......

**Comment by dropts** [comment]
代码都发出来了，复制都不会复制，离谱。
