### ISSUE TITLE
pt_pin 如果是中文，任务提示失败

### ISSUE THREAD

**Issue by conghuahuadan** [KingRan/KR#89]
如图，pt_pin 是中文，则请求失败，改成英文则正常
![image](https://user-images.githubusercontent.com/20864280/163600620-30751d69-510f-4156-a5a8-bdcbfb25d543.png)

**Comment by KingRan** [comment]
需要自己转码

**Comment by conghuahuadan** [comment]
大佬，可以具体点吗，怎么转

**Comment by vicat47** [comment]
urlencode 一下
